apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "traefik"
  labels:
  name: firefly-iii-importer-ingress
spec:
  rules:
  - host: importer-ffiii.lukemckechnie.com
    http:
      paths:
      - backend:
          service:
            name: firefly-iii-importer
            port:
              number: 8080
        path: /
        pathType: Prefix
# tls:
#  - hosts:
#    - importer-firefly-iii.your-domain.org
#    secretName: importer-firefly-iii.your-domain.org-tls

