apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-firefly-iii
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
