apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-firefly-iii-mysql
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  
